
export const SECTOR_GET_SECTOR = "SECTOR_GET_SECTOR"
export const SECTOR_GET_SECTOR_FAILURE = "SECTOR_GET_SECTOR_FAILURE"
export const SECTOR_GET_SECTOR_SUCCESS = "SECTOR_GET_SECTOR_SUCCESS"

export const SECTOR_MANAGER_REDUX_STATE_SECTOR = "SECTOR_MANAGER_REDUX_STATE_SECTOR"
