
export const ACCOUNT_GET_ACCOUNT = "ACCOUNT_GET_ACCOUNT"
export const ACCOUNT_GET_ACCOUNT_FAILURE = "ACCOUNT_GET_ACCOUNT_FAILURE"
export const ACCOUNT_GET_ACCOUNT_SUCCESS = "ACCOUNT_GET_ACCOUNT_SUCCESS"
export const ACCOUNT_MANAGER_REDUX_STATE_ACCOUNT = "ACCOUNT_MANAGER_REDUX_STATE_ACCOUNT"

export const ACCOUNT_CREATE_ACCOUNT = "ACCOUNT_CREATE_ACCOUNT"
export const ACCOUNT_CREATE_ACCOUNT_FAILURE = "ACCOUNT_CREATE_ACCOUNT_FAILURE"
export const ACCOUNT_CREATE_ACCOUNT_SUCCESS = "ACCOUNT_CREATE_ACCOUNT_SUCCESS"
export const ACCOUNT_UPDATE_ACCOUNT = "ACCOUNT_UPDATE_ACCOUNT"
export const ACCOUNT_UPDATE_ACCOUNT_FAILURE = "ACCOUNT_UPDATE_ACCOUNT_FAILURE"
export const ACCOUNT_UPDATE_ACCOUNT_SUCCESS = "ACCOUNT_UPDATE_ACCOUNT_SUCCESS"
