
export const EMPLOYEE_GET_EMPLOYEE = "EMPLOYEE_GET_EMPLOYEE"
export const EMPLOYEE_GET_EMPLOYEE_FAILURE = "EMPLOYEE_GET_EMPLOYEE_FAILURE"
export const EMPLOYEE_GET_EMPLOYEE_SUCCESS = "EMPLOYEE_GET_EMPLOYEE_SUCCESS"
export const EMPLOYEE_MANAGER_REDUX_STATE_EMPLOYEE = "EMPLOYEE_MANAGER_REDUX_STATE_EMPLOYEE"

export const EMPLOYEE_CREATE_EMPLOYEE = "EMPLOYEE_CREATE_EMPLOYEE"
export const EMPLOYEE_CREATE_EMPLOYEE_FAILURE = "EMPLOYEE_CREATE_EMPLOYEE_FAILURE"
export const EMPLOYEE_CREATE_EMPLOYEE_SUCCESS = "EMPLOYEE_CREATE_EMPLOYEE_SUCCESS"
