
export const EMPLOYEE_GET_ALL_EMPLOYEE = "EMPLOYEE_GET_ALL_EMPLOYEE"
export const EMPLOYEE_GET_ALL_EMPLOYEE_FAILURE = "EMPLOYEE_GET_ALL_EMPLOYEE_FAILURE"
export const EMPLOYEE_GET_ALL_EMPLOYEE_SUCCESS = "EMPLOYEE_GET_ALL_EMPLOYEE_SUCCESS"
