
export const LOCAL_SET_LOCAL_STATE = "LOCAL_SET_LOCAL_STATE"
export const LOCAL_SET_LOCAL_STATE_FAILURE = "LOCAL_SET_LOCAL_STATE_FAILURE"
export const LOCAL_SET_LOCAL_STATE_SUCCESS = "LOCAL_SET_LOCAL_STATE_SUCCESS"
