
export const PAYROLL_GET_ALL_PAYROLL = "PAYROLL_GET_ALL_PAYROLL"
export const PAYROLL_GET_ALL_PAYROLL_FAILURE = "PAYROLL_GET_ALL_PAYROLL_FAILURE"
export const PAYROLL_GET_ALL_PAYROLL_SUCCESS = "PAYROLL_GET_ALL_PAYROLL_SUCCESS"
export const PAYROLL_CREATE_PAYROLL = "PAYROLL_CREATE_PAYROLL"
export const PAYROLL_CREATE_PAYROLL_FAILURE = "PAYROLL_CREATE_PAYROLL_FAILURE"
export const PAYROLL_CREATE_PAYROLL_SUCCESS = "PAYROLL_CREATE_PAYROLL_SUCCESS"
export const PAYROLL_MANAGER_REDUX_STATE_PAYROLL = "PAYROLL_MANAGER_REDUX_STATE_PAYROLL"
