export const WEB_SERVICE_API = process.env.REACT_APP_WEB_SERVICE_API
export const WEB_SERVICE_API_LOGIN = `${WEB_SERVICE_API}/auth/login`
export const WEB_SERVICE_API_PERSONAL_MENU = `${WEB_SERVICE_API}/activity/personal_menu`
export const WEB_SERVICE_API_EMPLOYEE_ALL = `${WEB_SERVICE_API}/employees/collection`
export const WEB_SERVICE_API_EMPLOYEE_CREATE = `${WEB_SERVICE_API}/employees`
export const WEB_SERVICE_API_PROVINCES_ALL = `${WEB_SERVICE_API}/provinces`
export const WEB_SERVICE_API_MUNICIPALITY_ALL = `${WEB_SERVICE_API}/municipalities`
export const WEB_SERVICE_API_SECTOR_PROVINCES_ALL = `${WEB_SERVICE_API}/sectors`
export const WEB_SERVICE_API_DEPARTMENT_ALL = `${WEB_SERVICE_API}/departments/all`
export const WEB_SERVICE_API_DEPARTMENT_CREATE = `${WEB_SERVICE_API}/departments`
export const WEB_SERVICE_API_POSITION_ALL = `${WEB_SERVICE_API}/positions/all`
export const WEB_SERVICE_API_POSITION_DEPARTMENT= `${WEB_SERVICE_API}/positions/department`
export const WEB_SERVICE_API_POSITION_CREATE = `${WEB_SERVICE_API}/positions`
export const WEB_SERVICE_API_PAYROLL_RECORD = `${WEB_SERVICE_API}/payroll/collection`
export const WEB_SERVICE_API_PAYROLL_CREATE = `${WEB_SERVICE_API}/payroll`
export const WEB_SERVICE_API_PAYROLL_RECORD_CREATE = `${WEB_SERVICE_API}/payroll-record`
