export const PATH_LOGIN='/login'
export const PATH_MAIN='/'
export const PATH_FIXED_CONSULTING='/fixed_payroll/consulting'
export const PATH_CONFIG_EMPLOYEE_CONSULTING='config/employee/register'
export const PATH_CONFIG_DEPARTMENT_CONSULTING='/config/departments/register'
export const PATH_CONFIG_POSITIONS_CONSULTING='/config/positions/register'