export const PAYROLL_NEWS_GET_COLLECTION = "PAYROLL_NEWS_GET_COLLECTION";
export const PAYROLL_NEWS_GET_COLLECTION_FAILURE =
  "PAYROLL_NEWS_GET_COLLECTION_FAILURE";
export const PAYROLL_NEWS_GET_COLLECTION_SUCCESS =
  "PAYROLL_NEWS_GET_COLLECTION_SUCCESS";
export const PAYROLL_NEWS_CREATE_PAYROLL_NEWS =
  "PAYROLL_NEWS_NEWS_CREATE_PAYROLL_NEWS";
export const PAYROLL_NEWS_CREATE_PAYROLL_NEWS_FAILURE =
  "PAYROLL_NEWS_CREATE_PAYROLL_NEWS_FAILURE";
export const PAYROLL_NEWS_CREATE_PAYROLL_NEWS_SUCCESS =
  "PAYROLL_NEWS_CREATE_PAYROLL_NEWS_SUCCESS";
export const PAYROLL_NEWS_MANAGER_REDUX_STATE_PAYROLL_NEWS =
  "PAYROLL_NEWS_MANAGER_REDUX_STATE_PAYROLL_NEWS";
